### ISSUE TITLE
Support for rich message formatting / attachments 

### ISSUE THREAD

**Issue by johntdyer** [kenjij/lita-slack#30]
Does the lita slack plugin support and rich data formatting.  Slack calls this API `message attachments` and its linked [here](https://api.slack.com/docs/attachments)

**Comment by jimmycuadra** [comment]
Not yet, but this is a desired feature! The big question is it should work, given the constraints that Lita works for multiple chat services. There is no equivalent of Slack's attachments in other chat services, so having a separate API for it would have to be Lita-adapter-specific, limiting the interoperability of an open source plugin.

Lita 4.2 introduced a template system that allows adapter-specific messages, but Slack attachments are more complicated than formatting. Creating one requires a separate method call with multiple fields in the payload.

I'd love to hear people's thoughts on how support for Slack attachments might be approached.

**Comment by johntdyer** [comment]
Yea, I am not well versed enough w/ the Lita API to suggest anything at the moment.  Can you point out exactly where the problem is so I know where to focus my investigation?

**Comment by jimmycuadra** [comment]
`Lita::Adapter` is the class that has methods common to all chat services. All the methods are something generic like "send_messages." It wouldn't make sense to have a Slack-specific method on the base adapter because it's not common functionality.

Another possibility is to use the event system. lita-slack could listen for an event like "send_attachment" and then handlers could trigger the event rather than calling a method on the robot/adapter. This seems like a hacky solution, though, and I'd really like something better.

There's also the issue that Slack attachments are not currently supported by their real time messaging API, so this issue is sort of blocked for now anyway. See jimmycuadra/lita#89 for more discussion on this.

**Comment by MrJoy** [comment]
Suggestion:  It looks like whatever gets passed to `reply` is sent to the adapter unadulterated.  Make a class representing a message with an attachment, whose `to_s` returns the fallback value.  Use `is_a?` to determine if the payload you got is of this type and handle it gracefully if it is.

**Comment by brodock** [comment]
It's not only Slack which supports some sort of "meta formatting", look at HipChat documentation as an example: https://www.hipchat.com/docs/apiv2/method/send_room_notification


Expanding @MrJoy alternative, Lita could have a "send_rich_message" which would receive an adapter indexed hash of objects that could do rich formatting, and fallback to a default "clear text" one.

take this example:

```ruby
{
  slack: SlackRichMessage.new(title: 'Zomg Title', pretext: 'Wait for it...', text: 'Wazaap', color: '#36a64f'),
  hipchat: HipChatRichMessage.new(color: 'yellow', message: 'Wazaap')
  default: 'Wazaap'
}
```

this is very flexible, as we could do whatever structure we want, for example, let's compose 2 "attachments" into one message:

```ruby
slack_attachments = SlackRichMessage.new
slack_attachments.add title: 'Zomg Title', pretext: 'Wait for it...', text: 'Wazaap', color: '#36a64f'
slack_attachments.add title: 'Zomg Title 2', pretext: 'Wait for it... again...', text: 'Wazaap2', color: '#36a64f'

{
  slack: slack_attachments,
  hipchat: HipChatRichMessage.new(color: 'yellow', message: 'Wazaap')
  default: 'Wazaap'
}
```

what do you think @jimmycuadra ?

**Comment by jimmycuadra** [comment]
It'd be a problem for open source plugins to add adapter-specific functionality in that example, because objects like `SlackRichMessage` wouldn't exist unless you either add the adapter as a dependency of the handler, or add some annoying conditional/late loading logic.

**Comment by brodock** [comment]
Hmmm that's true... let's try a different approach:

```ruby
class RichMessage
  def initialize(default)
    # default text when current adapter is not defined
    @adapters = {default: default}
  end

  def add(adapter, args*)
    if @adapters[adapter]
      # this will be used by messages with composed definitions (a.k.a. Slack Attachments)
      if @adapters[adapter].is_a? Array
        @adapters[adapter] << args
      else
        @adapters[adapter] = [@adapters[adapter], args]
      end
    else
      @adapters[adapter] = args
    end

   self
  end
end

def rich_message(default)
  RichMessage.new(default)
end

message = rich_message('Wazaap').add(:hipchat, color: 'yellow', message: 'Wazaap')
message.add(:slack, title: 'Zomg Title', pretext: 'Wait for it...', text: 'Wazaap', color: '#36a64f').add(:slack, title: 'Zomg Title 2', pretext: 'Wait for it... again...', text: 'Wazaap2', color: '#36a64f')

send_rich_message(message)
```

With this more generic approach, every adapter can use the metadata in the way they need it.

**Comment by jimmycuadra** [comment]
Definitely an interesting idea. I will keep thinking on it. Thanks, @brodock.

**Comment by johntdyer** [comment]
@jimmycuadra:  Any chance you've had an opportunity to noodle this ? Thanks

-John

**Comment by jimmycuadra** [comment]
Yes, but there's no obvious approach to take yet. I'm leaning towards having some API for adapter-specific methods rather than trying to create an abstraction for something like "rich messages" which aren't universal.

**Comment by rmoriz** [comment]
Is there an easy work-around/hack to currently reply with attachments/formatting?

**Comment by clintkelly** [comment]
Supporting attachments would be awesome.  I would be fine with having some slack-specific code for this (we use Lita only for Slack currently), or doing something like what @brodock suggested.

**Comment by clintkelly** [comment]
FWIW the RTM for Slack does not even support links (e.g., `<http://google.com|google>`) even though the documentation states pretty explicitly that it does.  Some kind of support for rich formatting would be awesome.  :+1:

**Comment by jaisonerick** [comment]
I'm working on something to handle this:
https://github.com/kenjij/lita-slack/compare/master...jaisonerick:feature/slack-full-messages

The usage would be something like:

```ruby
response.reply(text: 'Main text', attachments: [{text: 'Attachment Text'}]) # Sends complex messages
response.reply('Main Text') # Send plain old slack messages
```

The contents of the reply are forwarded to the [chat.postMessages](https://api.slack.com/methods/chat.postMessage) slack api method. The `channel` param is handled by [`channel_for`](https://github.com/kenjij/lita-slack/blob/master/lib/lita/adapters/slack.rb#L41) method. The `as_user` param is set as true to be compliant with the current reply method's behavior.

The drawback of this approach is that it's not compatible with other adapters, so if your handler uses it, you'll only support Slack, but as it is intended to be used only on internal handlers (not on open sourced ones), it would be fine.

One approach to support all adapters would be to implement something like that on Lita project itself, having some sort of RichMessage class, like the one in @brodock solution. I did something like that using a simple class:

``` ruby
class Message
  def initialize(message)
    @message = message
  end

  def to_slack
    @message
  end

  def to_s
    @message[:text]
  end
end
```

The idea here is that the **handler** would define this class, implementing any **to_<adapter>** methods supported, and lita would call the adapter correspondent method. If the adapter isn't supported, it would fallback to the `to_s` method. To support this, the following change is needed on Lita project:

https://github.com/jimmycuadra/lita/blob/master/lib/lita/robot.rb#L125

```ruby
def send_messages(target, *messages)
  message_method = "to_#{config.robot.adapter}".to_sym

  messages = messages.flatten.map do |message|
    if message.respond_to(message_method)
      message.send(message_method) 
   else
      message.to_s
    end
  end

  adapter.send_messages(target, messages)
end
```

Of course, if the former change, on Lita project, was implemented, the first one would break, because everything would be converted to string.

**Comment by jimmycuadra** [comment]
Thank you, Jaison, that is very useful. I may end up implementing something very similar to this.

**Comment by jimmycuadra** [comment]
Support for attachments has finally been added in [version 1.6.0](https://github.com/kenjij/lita-slack/releases/tag/v1.6.0). Thank you everyone for your participation in the discussion and for your patience!

**Comment by assimovt** [comment]
Awesome :heart_eyes_cat: Any docs on how to use the new "chat service" API?

**Comment by jimmycuadra** [comment]
Yes, see the updated README.md. The generated docs on rubydoc.info may not have updated yet, so in the meantime you can generate them yourself locally with `gem install yard && yard` from the root of the repository, or you could just read the inline comments in the code itself. lib/lita/adapters/slack/chat_service.rb is the file you want.

**Comment by assimovt** [comment]
Got it @jimmycuadra Thanks for this update.

However, I am trying to send other parameters as well, such as ```icon_url```, for which I also need to send ```as_user: false``` and give a ```username```. Is it possible to do it with current version?

**Comment by byalpel** [comment]
You rock Jimmy!

**Comment by jimmycuadra** [comment]
@assimovt Does this mean you're trying to create attachments that don't appear as your Lita bot? In the current implementation `as_user` is hardcoded so that they all appear as messages from Lita in the chat. I don't really intend the Slack adapter to serve as a generic API client for Slack, but I'd be curious to hear more about your use case.

**Comment by assimovt** [comment]
@jimmycuadra Yes I am trying to use different icon based on the response of API that my custom Lita handler is interacting with.

**Comment by jimmycuadra** [comment]
For anyone else who lands here looking for docs, I added sections about this to docs.lita.io:

http://docs.lita.io/plugin-authoring/adapters/#chat-service
http://docs.lita.io/plugin-authoring/handlers/#chat-service
