### ISSUE TITLE
Lita stops if Slack closes websocket

### ISSUE THREAD

**Issue by Igorshp** [kenjij/lita-slack#38]
We've been having this problem for few months. Occasionally lita would simply 'crash' and stop working with no stacktrace.

I've traced it down to this:
https://github.com/kenjij/lita-slack/blob/master/lib/lita/adapters/slack/rtm_connection.rb#L48

It looks like when websocket gets closed upstream by Slack, the whole Eventloop gets stopped instead of retry.

Is this intended behaviour? Shouldn't connection be reopened?

**Comment by jimmycuadra** [comment]
Yes, it's intended, though it should be documented better because it's not really obvious that this will happen. Lita will shut down cleanly if the connection is lost so that whatever init system/process manager is supervising the process can restart it in a clean state.

Not everyone agrees with this approach, so it's something that may be changed in the future. There's been some discussion at jimmycuadra/lita-hipchat#20 if you'd like to follow that. In the meantime, I'd be happy to accept a PR clarifying how this works in the project's README.
